### ISSUE TITLE
How to extract texture mesh from NeRF?

### ISSUE THREAD

**Issue by ymxbj** [NIRVANALAN/LN3Diff#1]
Dear authors, thank you very much for your wonderful work! But I wonder how to get a texture mesh from generative NeRF. The current code only save a mesh file without color. Is it possible to get a texture mesh with color information on its every vertex？
Looking forward for your reply, thanks!

**Comment by NIRVANALAN** [comment]
Hi, thanks for your interest in our work. Yes it is fully compatible to get a textured mesh from the current pipeline by saving the color as an attribute when porting the ply file. I will update the code soon to support this function and let you know asap.

**Comment by NIRVANALAN** [comment]
Hi, I have updated the mesh export code [here](https://github.com/NIRVANALAN/LN3Diff/blob/26797c03193e5073ef586edccc9b4d3b289393ef/nsr/train_util.py#L627) to include vertex color to the saved ply file. The  demo VAE reconstruction mesh now looks like the following. Since t23d and vae reconstruction are calling the same [visualization function](https://github.com/NIRVANALAN/LN3Diff/blob/26797c03193e5073ef586edccc9b4d3b289393ef/nsr/train_util.py#L564), colored mesh export shall work for the both.

![image](https://github.com/NIRVANALAN/LN3Diff/assets/23359323/9306abd2-89d9-417c-95f5-5f923604121a)

Please let me know if there are any issues.
